### PR TITLE
fix: silent log level does not work #97

### PR DESCRIPTION
**Pull request by regevbr**
fix: #97

### CODE REVIEW

**Comment by regevbr** [comment]
haha @pi0 sorry to bother you so much, but can you look into it please?

**Comment by regevbr** [comment]
I also added a verbose log level which complements the silent log level.
In addition I also fixed some more typings issues I discovered along the way

**Comment by regevbr** [comment]
@pi0 can you please CR this?

**Comment by regevbr** [comment]
Thanks @pi0

**Comment by pi0** [comment]
No problems. If you are interested helping for package maintenance, I can send an invitation :)

**Comment by regevbr** [comment]
Thanks for proposal! Sure that will be great 😊 my time is limited now but I would love to help where I can

**Pull request merged**
